# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Debian-7-amd64-vbox"

  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.ssh.username = "dynatrace"
  config.ssh.private_key_path = "../../keys/dynatrace"

end
