---
- name: Update APT cache
  apt: update_cache=yes
  sudo: yes

- name: Install package 'curl'
  apt: pkg=curl state=present
  sudo: yes

- name: Check if 'java' is on the PATH
  shell: which java
  sudo: yes
  ignore_errors: yes
  register: which_java_cmd

- name: Install package 'default-jre'
  apt: pkg=default-jre state=present
  register: default_jre_installed
  when: which_java_cmd.rc != 0
  sudo: yes
