---
- name: Copy the Dynatrace installer to {{ dynatrace_install_dir }}
  copy: src={{ dynatrace_full_installer_linux_file }} dest="{{ dynatrace_install_dir }}"
  sudo: yes

- name: Stop and disable running Dynatrace services
  service: name={{ item }} state=stopped enabled=no
  with_items: dynatrace_server_services
  sudo: yes
  ignore_errors: yes

- name: Sleep for 5 seconds...
  pause: seconds=5

- name: Install Dynatrace
  shell: yes | java -jar {{ dynatrace_full_installer_linux_file }} chdir={{ dynatrace_install_dir }}
  sudo: yes

- name: Gather the name of the Dynatrace version installation directory
  shell: find . -maxdepth 1 -name dynatrace-\* -type d -printf '%T@ %p\n' | sort -k 1nr | cut -d' ' -f2 | head -1 chdir={{ dynatrace_install_dir }}
  register: dynatrace_installed_version_dir
  sudo: yes
- debug: msg="Dynatrace installed version directory? {{ dynatrace_installed_version_dir.stdout }}"

- name: Change ownership of the Dynatrace installation directory
  file: path={{ dynatrace_install_dir }}/{{ dynatrace_installed_version_dir.stdout }} owner=dynatrace group=dynatrace state=directory recurse=yes
  sudo: yes

- name: Change mode of the Dynatrace installation directory
  file: path={{ dynatrace_install_dir }}/{{ dynatrace_installed_version_dir.stdout }} mode=0700
  sudo: yes

- name: Create a symlink of the concrete Dynatrace installation directory to {{ dynatrace_install_dir }}/dynatrace
  file: src={{ dynatrace_install_dir }}/{{ dynatrace_installed_version_dir.stdout }} dest={{ dynatrace_install_dir }}/dynatrace owner=dynatrace group=dynatrace mode=0700 state=link
  sudo: yes

- name: Remove the Dynatrace installer
  file: path="{{ dynatrace_install_dir }}/{{ dynatrace_full_installer_linux_file }}" state=absent
  sudo: yes

- include: install-dynatrace-initd-scripts.yml

- name: Configure the collector host in the 'dtwsagent.ini' file
  lineinfile: dest={{ dynatrace_install_dir }}/dynatrace/agent/conf/dtwsagent.ini regexp='^Server .*' line='Server {{ dynatrace_collector_host }}'
  sudo: yes

- name: Enable and start Dynatrace services
  service: name={{ item }} state=restarted sleep=5 enabled=yes
  with_items: dynatrace_server_services
  sudo: yes
