---
- name: Remove package 'curl'
  yum: name=curl state=absent
  sudo: yes

- name: Remove package 'default-jre'
  yum: pkg=default-jre state=absent
  when: default_jre_installed|success
  sudo: yes
