---
- name: Enable SSH public key authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp='^\#?PubkeyAuthentication.*' line='PubkeyAuthentication yes' state=present
  sudo: yes
  notify: reload sshd

- name: Disable password authentication via SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp='^\#?PasswordAuthentication.*' line='PasswordAuthentication no' state=present
  sudo: yes
  notify: reload sshd
